# Generated by Django 4.2.3 on 2023-08-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0006_studytask"),
    ]

    operations = [
        migrations.AddField(
            model_name="studytask",
            name="pathway",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="pathways.pathway",
            ),
            preserve_default=False,
        ),
    ]
