# Generated by Django 4.2.3 on 2023-08-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0008_studytask_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_type",
                    models.CharField(
                        choices=[
                            ("first", "First Revision"),
                            ("second", "Second Revision"),
                            ("third", "Third Revision"),
                            ("fourth", "Fourth Revision"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "study_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="pathways.studytask",
                    ),
                ),
            ],
        ),
    ]
