# Generated by Django 4.2.3 on 2023-08-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0009_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="pathway",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="pathways.pathway",
            ),
            preserve_default=False,
        ),
    ]
