# Generated by Django 4.2.3 on 2023-09-03 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pathways", "0013_followedpathway"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="followedpathway",
            unique_together={("user", "pathway")},
        ),
    ]
