# Generated by Django 4.2.3 on 2023-09-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0015_fileresource_created_by_imageresource_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkresource",
            name="fetched_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linkresource",
            name="fetched_title",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
