# Generated by Django 4.2.3 on 2023-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0016_linkresource_fetched_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkresource",
            name="fetched_domain",
            field=models.URLField(blank=True, null=True),
        ),
    ]
