# Generated by Django 4.2.3 on 2023-09-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0020_fileresource_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileresource",
            name="cloudinary_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
