# Generated by Django 4.2.3 on 2023-09-09 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0022_remove_fileresource_cloudinary_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
