# Generated by Django 4.2.3 on 2023-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0023_revision_created_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revision",
            name="revision_type",
        ),
        migrations.RemoveField(
            model_name="revision",
            name="status",
        ),
        migrations.AddField(
            model_name="revision",
            name="first_revision_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="fourth_revision_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="overall_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="second_revision_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="third_revision_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
