# Generated by Django 4.2.3 on 2023-09-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0026_studytask_is_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textresource",
            name="content",
            field=models.TextField(),
        ),
    ]
