# Generated by Django 4.2.3 on 2023-09-11 15:05

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0027_alter_textresource_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textresource",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
