# Generated by Django 4.2.3 on 2023-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pathways",
            "0029_alter_fileresource_notes_alter_imageresource_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkresource",
            name="notes",
            field=models.TextField(),
        ),
    ]
