# Generated by Django 4.2.3 on 2023-09-11 16:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pathways", "0030_alter_linkresource_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkresource",
            name="notes",
            field=django_quill.fields.QuillField(),
        ),
    ]
